import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BlessedHeader from "./BlessedHeader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Blessed Only",
  description: "Generated by Astro Nova Labs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <BlessedHeader />
        {children}</body>
    </html>
  );
}
